import {useEffect,useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {Archive,Check,Clipboard,History,KeyRound,Palette,RefreshCw,Settings,ShieldCheck,UserPlus,X} from 'lucide-react';
import {toast} from 'sonner';
import {Badge,Button,Card,FieldHelp,Input,Select} from '../components/ui';
import {canManage,isGroupOwner,useGroup} from '../hooks/useGroup';
import {supabase} from '../lib/supabase';
import {fullName} from '../lib/utils';
import {useRealtimeInvalidation} from '../hooks/useRealtime';

type JoinRequest={request_id:string;user_id:string;first_name:string;last_name:string;preferred_position:string|null;preferred_positions:string[]|null;created_at:string};
export default function GroupSettingsPage(){
 const {data:g}=useGroup();const qc=useQueryClient();const [f,setF]=useState({name:'',description:'',default_location:'',visibility:'public',join_mode:'approval_required',theme_color:'#2563eb'});const owner=isGroupOwner(g);const canManageMembers=canManage(g,'manage_members');
 useEffect(()=>{if(g)setF({name:g.group.name||'',description:g.group.description||'',default_location:g.group.default_location||'',visibility:g.group.visibility||'public',join_mode:g.group.join_mode||'approval_required',theme_color:g.group.theme_color||'#2563eb'})},[g?.group.id]);
 const requestsKey=['join-requests',g?.group.id];
 const {data:requests=[],isLoading,error}=useQuery({queryKey:requestsKey,enabled:!!g&&canManageMembers,queryFn:async()=>{const {data,error}=await supabase.rpc('list_group_join_requests',{p_group_id:g!.group.id});if(error)throw error;return (data||[]) as JoinRequest[]}});
 const {data:members=[]}=useQuery({queryKey:['settings-members',g?.group.id],enabled:!!g&&owner,queryFn:async()=>{const {data,error}=await supabase.from('group_members').select('user_id,role,status,profiles(first_name,last_name)').eq('group_id',g!.group.id).eq('status','active');if(error)throw error;return data||[]}});
 const {data:audit=[]}=useQuery({queryKey:['group-audit',g?.group.id],enabled:!!g&&canManageMembers,queryFn:async()=>{const {data,error}=await supabase.from('audit_logs').select('*').eq('group_id',g!.group.id).order('created_at',{ascending:false}).limit(30);if(error)throw error;return data||[]}});
 useRealtimeInvalidation(`join-requests-${g?.group.id}`,['group_join_requests'],[requestsKey],!!g&&canManageMembers);
 const save=useMutation({mutationFn:async()=>{const before=g!.group;const patch={name:f.name.trim(),description:f.description.trim()||null,default_location:f.default_location.trim()||null,visibility:f.visibility,join_mode:f.join_mode,theme_color:f.theme_color,updated_at:new Date().toISOString()};const {error}=await supabase.from('groups').update(patch).eq('id',g!.group.id);if(error)throw error;await supabase.rpc('log_group_audit',{p_group_id:g!.group.id,p_action:'group.updated',p_entity_type:'group',p_entity_id:g!.group.id,p_old:before,p_new:patch})},onSuccess:()=>{toast.success('פרטי הקבוצה עודכנו');qc.invalidateQueries({queryKey:['my-groups']});qc.invalidateQueries({queryKey:['group-catalog']});qc.invalidateQueries({queryKey:['group-audit']})},onError:(e:any)=>toast.error(e.message)});
 const review=async(id:string,approve:boolean)=>{const {error}=await supabase.rpc('review_group_join_request',{p_request_id:id,p_approve:approve});if(error)toast.error(error.message);else{toast.success(approve?'השחקן צורף':'הבקשה נדחתה');await qc.invalidateQueries()}};
 const rotate=useMutation({mutationFn:async()=>{const {data,error}=await supabase.rpc('rotate_group_invite_code',{p_group_id:g!.group.id});if(error)throw error;return data as string},onSuccess:code=>{toast.success('קוד ההזמנה הוחלף');qc.invalidateQueries({queryKey:['my-groups']});navigator.clipboard?.writeText(`${location.origin}/join/${code}`)},onError:(e:any)=>toast.error(e.message)});
 const archive=useMutation({mutationFn:async()=>{const {error}=await supabase.rpc('archive_group',{p_group_id:g!.group.id,p_restore:false});if(error)throw error},onSuccess:()=>{toast.success('הקבוצה הועברה לארכיון');qc.invalidateQueries({queryKey:['my-groups']});location.assign('/groups')},onError:(e:any)=>toast.error(e.message)});
 const transfer=useMutation({mutationFn:async(userId:string)=>{const {error}=await supabase.rpc('transfer_group_ownership',{p_group_id:g!.group.id,p_new_owner:userId});if(error)throw error},onSuccess:()=>{toast.success('הבעלות הועברה');qc.invalidateQueries();location.reload()},onError:(e:any)=>toast.error(e.message)});
 const inviteUrl=useMemo(()=>g?.group.invite_code?`${location.origin}/join/${g.group.invite_code}`:'',[g?.group.invite_code]);
 if(!canManage(g))return <Card>אין לך הרשאת ניהול לקבוצה הזאת.</Card>;
 return <div className="space-y-5"><div className="page-heading"><div><p>מועדון, הצטרפות, בעלות ובקרה</p><h1>הגדרות הקבוצה</h1></div><Settings/></div>
  <Card className="form-card"><div><h2>זהות ומדיניות המועדון</h2><p>הפרטים האלה שולטים באופן שבו משתמשים מגלים ומצטרפים לקבוצה.</p></div><div className="form-grid"><div><FieldHelp title="שם הקבוצה">אפשר לשנות בלי לפגוע בהיסטוריה.</FieldHelp><Input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></div><div><FieldHelp title="מיקום קבוע">המגרש שבו משחקים בדרך כלל.</FieldHelp><Input value={f.default_location} onChange={e=>setF({...f,default_location:e.target.value})}/></div><div><FieldHelp title="נראות">קבוצה פרטית אינה מופיעה בגילוי.</FieldHelp><Select value={f.visibility} onChange={e=>setF({...f,visibility:e.target.value})}><option value="public">ציבורית</option><option value="private">פרטית</option></Select></div><div><FieldHelp title="מדיניות הצטרפות">אפשר להצטרף מיד, באישור או רק בהזמנה.</FieldHelp><Select value={f.join_mode} onChange={e=>setF({...f,join_mode:e.target.value})}><option value="open">פתוחה</option><option value="approval_required">באישור מנהל</option><option value="invite_only">הזמנה בלבד</option></Select></div><div className="md:col-span-2"><FieldHelp title="תיאור הקבוצה">מידע קצר לשחקנים.</FieldHelp><Input value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></div><div><FieldHelp title="צבע המועדון"><Palette size={14}/> מוצג בכותרת ובכרטיסים.</FieldHelp><Input type="color" value={f.theme_color} onChange={e=>setF({...f,theme_color:e.target.value})}/></div></div><Button disabled={!f.name.trim()||save.isPending} onClick={()=>save.mutate()}>שמירת שינויים</Button></Card>
  {owner&&<Card><div className="section-title"><h2><KeyRound/>קישור הזמנה</h2><Badge>לבעלים בלבד</Badge></div><p className="empty-inline">הקישור מצרף שחקנים ישירות לקבוצה. החלפת הקוד מבטלת מיד קישורים ישנים.</p><div className="action-row"><Input readOnly value={inviteUrl}/><Button variant="secondary" onClick={()=>{navigator.clipboard?.writeText(inviteUrl);toast.success('הקישור הועתק')}}><Clipboard size={16}/>העתקה</Button><Button variant="secondary" onClick={()=>rotate.mutate()}><RefreshCw size={16}/>החלפת קוד</Button></div></Card>}
  {canManageMembers&&<Card><div className="section-title"><h2><UserPlus/>בקשות הצטרפות</h2><Badge>{requests.length}</Badge></div>{isLoading?<p className="empty-inline">טוען בקשות...</p>:error?<p className="empty-inline">לא הצלחנו לטעון: {error instanceof Error?error.message:'שגיאה'}</p>:<div className="join-request-list">{requests.map(r=><div key={r.request_id}><div className="player-avatar">{r.first_name?.[0]||'ש'}</div><div><strong>{fullName({first_name:r.first_name,last_name:r.last_name} as any)}</strong><span>{new Date(r.created_at).toLocaleDateString('he-IL')}</span></div><div><Button onClick={()=>review(r.request_id,true)}><Check size={16}/>אישור</Button><Button variant="danger" onClick={()=>review(r.request_id,false)}><X size={16}/>דחייה</Button></div></div>)}{!requests.length&&<p className="empty-inline">אין בקשות שממתינות לאישור.</p>}</div>}</Card>}
  {owner&&<Card><div className="section-title"><h2><ShieldCheck/>בעלות ומחזור חיים</h2><Badge>פעולות רגישות</Badge></div><div className="form-grid"><div><FieldHelp title="העברת בעלות">הבעלים החדש חייב להיות חבר פעיל בקבוצה.</FieldHelp><Select defaultValue="" onChange={e=>e.target.value&&confirm('להעביר בעלות?')&&transfer.mutate(e.target.value)}><option value="">בחר חבר...</option>{members.filter((m:any)=>m.user_id!==g?.member.user_id).map((m:any)=><option key={m.user_id} value={m.user_id}>{fullName(m.profiles as any)}</option>)}</Select></div></div><Button variant="danger" onClick={()=>confirm('הקבוצה תועבר לארכיון ותוסתר מהחברים. להמשיך?')&&archive.mutate()}><Archive size={16}/>ארכוב קבוצה</Button></Card>}
  {canManageMembers&&<Card><div className="section-title"><h2><History/>Audit Log</h2><Badge>{audit.length}</Badge></div><div className="audit-list">{audit.map((a:any)=><div key={a.id}><strong>{a.action}</strong><span>{new Date(a.created_at).toLocaleString('he-IL')}</span><small>{a.entity_type}</small></div>)}{!audit.length&&<p className="empty-inline">עדיין אין פעולות מתועדות.</p>}</div></Card>}
 </div>;
}
