import {useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {useNavigate} from 'react-router-dom';
import {ChevronLeft,Clock3,KeyRound,Lock,MapPin,Plus,ShieldCheck,UsersRound,X} from 'lucide-react';
import {toast} from 'sonner';
import {Badge,Button,Card,FieldHelp,Input,Select} from '../components/ui';
import {useGroup} from '../hooks/useGroup';
import {supabase} from '../lib/supabase';
import {useAuth} from '../contexts/AuthContext';

export default function GroupsPage(){
 const {profile,signOut}=useAuth();const groups=useGroup();const qc=useQueryClient();const navigate=useNavigate();
 const [open,setOpen]=useState(false);const [invite,setInvite]=useState('');
 const [f,setF]=useState({name:'',description:'',default_location:'Gol Time',visibility:'public',join_mode:'approval_required',theme_color:'#2563eb'});
 const {data:catalog=[],isLoading,error}=useQuery({queryKey:['group-catalog',profile?.id],queryFn:async()=>{const {data,error}=await supabase.rpc('discover_groups');if(error)throw error;return data||[]}});
 const {data:archived=[]}=useQuery({queryKey:['my-archived-groups',profile?.id],queryFn:async()=>{const {data,error}=await supabase.rpc('my_archived_groups');if(error)throw error;return data||[]}});
 const activeIds=useMemo(()=>new Set(groups.memberships.map(x=>x.group.id)),[groups.memberships]);
 const available=useMemo(()=>catalog.filter((g:any)=>!activeIds.has(g.group_id)),[catalog,activeIds]);
 const create=useMutation({mutationFn:async()=>{const {data,error}=await supabase.rpc('create_teamup_group',{p_name:f.name.trim(),p_description:f.description.trim()||null,p_location:f.default_location.trim()||null,p_visibility:f.visibility,p_join_mode:f.join_mode,p_theme_color:f.theme_color});if(error)throw error;return data as string},onSuccess:async id=>{toast.success('הקבוצה נוצרה ואתה הבעלים שלה');setOpen(false);await qc.invalidateQueries();localStorage.setItem('teamup_pending_group',id);navigate('/')},onError:(e:any)=>toast.error(e.message)});
 const request=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.rpc('request_group_join',{p_group_id:id});if(error)throw error;return id},onSuccess:async()=>{toast.success('בקשת ההצטרפות נשלחה');await qc.invalidateQueries({queryKey:['group-catalog']});await qc.invalidateQueries({queryKey:['my-groups']})},onError:(e:any)=>toast.error(e.message)});
 const cancel=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.rpc('cancel_group_join_request',{p_group_id:id});if(error)throw error},onSuccess:async()=>{toast.success('הבקשה בוטלה');await qc.invalidateQueries({queryKey:['group-catalog']})},onError:(e:any)=>toast.error(e.message)});
 const joinInvite=useMutation({mutationFn:async()=>{const {data,error}=await supabase.rpc('join_group_by_invite',{p_code:invite.trim()});if(error)throw error;return data as string},onSuccess:async id=>{toast.success('הצטרפת לקבוצה');setInvite('');await qc.invalidateQueries({queryKey:['my-groups']});localStorage.setItem('teamup_pending_group',id);navigate('/')},onError:(e:any)=>toast.error(e.message)});
 const enter=(id:string)=>{groups.setActiveGroupId(id);navigate('/')};
 const restore=useMutation({mutationFn:async(id:string)=>{const {error}=await supabase.rpc('archive_group',{p_group_id:id,p_restore:true});if(error)throw error},onSuccess:async()=>{toast.success('הקבוצה שוחזרה');await qc.invalidateQueries()},onError:(e:any)=>toast.error(e.message)});
 return <div className="groups-hub"><header className="groups-hub-header"><div><span>⚽ TEAMUP</span><h1>מרכז הקבוצות</h1><p>נהל כמה קבוצות, הצטרף לקהילה קיימת או פתח מועדון חדש.</p></div><div className="groups-user"><strong>{profile?.first_name||'שחקן'}</strong><button onClick={signOut}>יציאה</button></div></header>
  {!!groups.memberships.length&&<section><div className="section-title"><h2><ShieldCheck/>הקבוצות שלי</h2><Badge>{groups.memberships.length}</Badge></div><div className="group-card-grid">{groups.memberships.map(x=><Card key={x.group.id} className="group-discovery-card owned" style={{borderTopColor:x.group.theme_color||'#2563eb'}}><div className="group-logo" style={{background:x.group.theme_color||'#2563eb'}}>{x.group.name.slice(0,2)}</div><div><Badge>{x.group.owner_id===profile?.id?'בעלים':x.member.role==='admin'||x.member.role==='moderator'?'מנהל קבוצה':'שחקן'}</Badge><h2>{x.group.name}</h2><p>{x.group.description||'קבוצת כדורגל ב־TEAMUP'}</p><span><MapPin size={14}/>{x.group.default_location||'מיקום לא הוגדר'}</span></div><Button onClick={()=>enter(x.group.id)}>כניסה <ChevronLeft size={17}/></Button></Card>)}</div></section>}
  <section><div className="section-title"><h2><UsersRound/>גילוי קבוצות</h2><Button onClick={()=>setOpen(v=>!v)}><Plus size={17}/>יצירת קבוצה</Button></div>
   <Card className="invite-code-card"><div><KeyRound/><div><h3>יש לך קוד הזמנה?</h3><p>הדבק קוד או את החלק האחרון של קישור ההזמנה.</p></div></div><div className="action-row"><Input value={invite} onChange={e=>setInvite(e.target.value)} placeholder="לדוגמה: A1B2C3D4"/><Button disabled={!invite.trim()||joinInvite.isPending} onClick={()=>joinInvite.mutate()}>הצטרפות</Button></div></Card>
   {open&&<Card className="form-card group-create-card"><div><h2>פתיחת קבוצה חדשה</h2><p>אתה תהיה הבעלים ותוכל למנות מנהלים נוספים.</p></div><div className="form-grid"><div><FieldHelp title="שם הקבוצה">שם שיופיע לחברים ובחיפוש.</FieldHelp><Input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="לדוגמה: כוכבי סטאר בול"/></div><div><FieldHelp title="מגרש קבוע">אפשר לשנות אחר כך.</FieldHelp><Input value={f.default_location} onChange={e=>setF({...f,default_location:e.target.value})}/></div><div><FieldHelp title="נראות">קבוצה פרטית לא תופיע בחיפוש.</FieldHelp><Select value={f.visibility} onChange={e=>setF({...f,visibility:e.target.value})}><option value="public">ציבורית</option><option value="private">פרטית</option></Select></div><div><FieldHelp title="הצטרפות">איך שחקנים נכנסים לקבוצה.</FieldHelp><Select value={f.join_mode} onChange={e=>setF({...f,join_mode:e.target.value})}><option value="approval_required">בקשה ואישור מנהל</option><option value="open">הצטרפות מיידית</option><option value="invite_only">רק עם הזמנה</option></Select></div><div className="md:col-span-2"><FieldHelp title="תיאור">מי אתם ומתי אתם משחקים.</FieldHelp><Input value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></div><div><FieldHelp title="צבע מועדון">מופיע בכרטיס ובכותרת.</FieldHelp><Input type="color" value={f.theme_color} onChange={e=>setF({...f,theme_color:e.target.value})}/></div></div><Button disabled={!f.name.trim()||create.isPending} onClick={()=>create.mutate()}>יצירת הקבוצה</Button></Card>}
   {isLoading?<Card>טוען קבוצות...</Card>:error?<Card className="empty-state"><h2>לא הצלחנו לטעון קבוצות</h2><p>{error instanceof Error?error.message:'נסה לרענן'}</p></Card>:<div className="group-card-grid">{available.map((g:any)=>{const pending=g.request_status==='pending';const inviteOnly=g.join_mode==='invite_only';return <Card key={g.group_id} className="group-discovery-card" style={{borderTopColor:g.theme_color||'#2563eb'}}><div className="group-logo" style={{background:g.theme_color||'#2563eb'}}>{g.group_name.slice(0,2)}</div><div><div className="action-row"><Badge>{g.visibility==='private'?<><Lock size={12}/>פרטית</>:'ציבורית'}</Badge><Badge>{g.join_mode==='open'?'פתוחה להצטרפות':g.join_mode==='invite_only'?'הזמנה בלבד':'באישור מנהל'}</Badge></div><h2>{g.group_name}</h2><p>{g.description||'קבוצת כדורגל ב־TEAMUP'}</p><span><UsersRound size={14}/>{g.member_count} חברים</span>{g.default_location&&<span><MapPin size={14}/>{g.default_location}</span>}<small>מנהל: {g.owner_name||'מנהל הקבוצה'}</small></div>{inviteOnly?<Button variant="secondary" disabled><Lock size={16}/>נדרשת הזמנה</Button>:pending?<div className="action-row"><Button variant="secondary" disabled><Clock3 size={17}/>ממתין לאישור</Button><Button variant="ghost" disabled={cancel.isPending} onClick={()=>cancel.mutate(g.group_id)}><X size={16}/>ביטול</Button></div>:<Button variant="secondary" disabled={request.isPending} onClick={()=>request.mutate(g.group_id)}>{g.join_mode==='open'?'הצטרפות לקבוצה':'בקשת הצטרפות'}</Button>}</Card>})}{!available.length&&<Card className="empty-state"><UsersRound/><h2>אין קבוצות נוספות</h2><p>אפשר ליצור קבוצה חדשה או להצטרף עם קוד הזמנה.</p></Card>}</div>}</section>
 </div>;
}
