import {useEffect,useMemo,useState} from 'react';
import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {CheckCircle2,Crown,Medal,Star,Trophy,UserRound} from 'lucide-react';
import {toast} from 'sonner';
import {Badge,Button,Card,Select} from '../components/ui';
import {useAuth} from '../contexts/AuthContext';
import {useGroup} from '../hooks/useGroup';
import {supabase} from '../lib/supabase';
import {fullName} from '../lib/utils';
import {useRealtimeInvalidation} from '../hooks/useRealtime';

type Row={id:string;first_name:string;last_name:string;avg_rating:number;rating_count:number;mvp_count:number};
type Player={user_id:string;profiles:any};
const scoreLabels:Record<number,string>={1:'חלש',2:'מתחת לממוצע',3:'טוב',4:'טוב מאוד',5:'מצוין'};

export default function RatingsPage(){
 const {user}=useAuth();const {data:g}=useGroup();const qc=useQueryClient();
 const [selected,setSelected]=useState('');const [scores,setScores]=useState<Record<string,number>>({});const [mvp,setMvp]=useState('');
 const {data:board=[]}=useQuery({queryKey:['ratings',g?.group.id],enabled:!!g,queryFn:async()=>{const {data:members,error}=await supabase.from('group_members').select('user_id,profiles(*)').eq('group_id',g!.group.id).eq('status','active');if(error)throw error;const ids=(members||[]).map((x:any)=>x.user_id);if(!ids.length)return[];const [{data:ratings},{data:votes}]=await Promise.all([supabase.from('player_ratings').select('rated_user_id,overall_rating').in('rated_user_id',ids),supabase.from('mvp_votes').select('voted_user_id').in('voted_user_id',ids)]);return (members||[]).map((m:any)=>{const rs=(ratings||[]).filter((r:any)=>r.rated_user_id===m.user_id);return {id:m.user_id,...m.profiles,avg_rating:rs.length?rs.reduce((a:number,b:any)=>a+Number(b.overall_rating),0)/rs.length:Number(m.profiles.base_rating||3),rating_count:rs.length,mvp_count:(votes||[]).filter((v:any)=>v.voted_user_id===m.user_id).length}}).sort((a:any,b:any)=>b.avg_rating-a.avg_rating) as Row[]}});
 const {data:openMatches=[]}=useQuery({queryKey:['open-ratings',g?.group.id,user?.id],enabled:!!g&&!!user,queryFn:async()=>{const {data,error}=await supabase.from('matches').select('id,title,match_date,start_time').eq('group_id',g!.group.id).eq('ratings_open',true).order('match_date',{ascending:false});if(error)throw error;const ids=(data||[]).map((m:any)=>m.id);if(!ids.length)return[];const {data:mine,error:me}=await supabase.from('match_registrations').select('match_id').eq('user_id',user!.id).eq('registration_status','confirmed').in('match_id',ids);if(me)throw me;const allowed=new Set((mine||[]).map((x:any)=>x.match_id));return(data||[]).filter((m:any)=>allowed.has(m.id))}});
 const active=useMemo(()=>openMatches.find((m:any)=>m.id===selected)||openMatches[0],[openMatches,selected]);
 useEffect(()=>{if(active&&!selected)setSelected(active.id)},[active,selected]);
 const {data:players=[],isLoading:playersLoading}=useQuery({queryKey:['rating-players',active?.id,user?.id],enabled:!!active&&!!user,queryFn:async()=>{const {data:regs,error}=await supabase.from('match_registrations').select('user_id').eq('match_id',active.id).eq('registration_status','confirmed').neq('user_id',user!.id);if(error)throw error;const ids=(regs||[]).map((r:any)=>r.user_id);if(!ids.length)return[];const {data:profiles,error:pe}=await supabase.from('profiles').select('id,first_name,last_name,preferred_positions,preferred_position').in('id',ids);if(pe)throw pe;const map=new Map((profiles||[]).map((p:any)=>[p.id,p]));return ids.map(id=>({user_id:id,profiles:map.get(id)})).filter(x=>x.profiles) as Player[]}});
 const {data:existing}=useQuery({queryKey:['my-ratings',active?.id,user?.id],enabled:!!active&&!!user,queryFn:async()=>{const [{data:ratings,error},{data:vote,error:ve}]=await Promise.all([supabase.from('player_ratings').select('rated_user_id,overall_rating').eq('match_id',active.id).eq('rater_user_id',user!.id),supabase.from('mvp_votes').select('voted_user_id').eq('match_id',active.id).eq('voter_user_id',user!.id).maybeSingle()]);if(error)throw error;if(ve)throw ve;return{ratings:ratings||[],vote}}});
 useEffect(()=>{if(!existing)return;setScores(Object.fromEntries(existing.ratings.map((r:any)=>[r.rated_user_id,r.overall_rating])));setMvp(existing.vote?.voted_user_id||'')},[existing,active?.id]);
 useRealtimeInvalidation(`ratings-${g?.group.id}`,['player_ratings','mvp_votes','matches'],[['ratings',g?.group.id],['open-ratings',g?.group.id,user?.id],['my-ratings',active?.id,user?.id]],!!g);
 const submit=useMutation({mutationFn:async()=>{if(!active)throw new Error('בחר משחק');const rows=players.filter(p=>scores[p.user_id]).map(p=>({match_id:active.id,rater_user_id:user!.id,rated_user_id:p.user_id,overall_rating:scores[p.user_id],teamwork_rating:scores[p.user_id],attack_rating:scores[p.user_id],defense_rating:scores[p.user_id],effort_rating:scores[p.user_id],sportsmanship_rating:scores[p.user_id]}));if(!rows.length)throw new Error('בחר ציון לפחות לשחקן אחד');const {error}=await supabase.from('player_ratings').upsert(rows,{onConflict:'match_id,rater_user_id,rated_user_id'});if(error)throw error;if(mvp){const {error:ve}=await supabase.from('mvp_votes').upsert({match_id:active.id,voter_user_id:user!.id,voted_user_id:mvp},{onConflict:'match_id,voter_user_id'});if(ve)throw ve}},onSuccess:()=>{toast.success('הדירוג והצבעת ה־MVP נשמרו');qc.invalidateQueries({queryKey:['ratings']});qc.invalidateQueries({queryKey:['my-ratings']})},onError:(e:any)=>toast.error(e.message)});
 const completed=players.filter(p=>scores[p.user_id]).length;
 return <div className="space-y-5"><div className="page-heading"><div><p>מדרגים את מי ששיחק איתך בלבד</p><h1>דירוגים ו־MVP</h1></div>{active&&<Badge>{completed}/{players.length} דורגו</Badge>}</div>
 {openMatches.length>0?<Card className="rating-workspace"><div className="rating-intro"><div><p className="eyebrow">הדירוג שלך</p><h2>בחר משחק ואז דרג כל שחקן</h2><p>לחץ על אחד מהציונים בכל כרטיס. אפשר לחזור ולשנות עד שהמנהל יסגור את הדירוג.</p></div><Select value={active?.id||''} onChange={e=>{setSelected(e.target.value);setScores({});setMvp('')}}>{openMatches.map((m:any)=><option key={m.id} value={m.id}>{m.title} · {new Date(`${m.match_date}T12:00:00`).toLocaleDateString('he-IL')}</option>)}</Select></div>
 {playersLoading?<div className="empty-note">טוען את משתתפי המשחק...</div>:players.length===0?<div className="empty-state"><UserRound size={32}/><h3>אין שחקנים נוספים לדירוג</h3><p>רק שחקנים שהיו ברשימת המשתתפים המאושרים מופיעים כאן.</p></div>:<><div className="rating-player-grid">{players.map(p=>{const value=scores[p.user_id];return <article key={p.user_id} className={`rating-player-card ${value?'rated':''}`}><div className="rating-player-head"><div className="player-avatar">{p.profiles.first_name?.[0]||'ש'}</div><div><h3>{fullName(p.profiles)}</h3><p>{(p.profiles.preferred_positions||[p.profiles.preferred_position]).filter(Boolean).join(' · ')||'ללא עמדה'}</p></div>{value&&<CheckCircle2 size={20}/>}</div><div className="score-picker" aria-label={`דירוג ${fullName(p.profiles)}`}>{[1,2,3,4,5].map(n=><button key={n} type="button" className={value===n?'active':''} title={`${n} - ${scoreLabels[n]}`} onClick={()=>setScores(s=>({...s,[p.user_id]:n}))}><Star size={17} fill={value===n?'currentColor':'none'}/><span>{n}</span></button>)}</div><small className="score-description">{value?scoreLabels[value]:'בחר ציון מ־1 עד 5'}</small></article>})}</div>
 <div className="mvp-section"><div><Crown size={23}/><div><h3>מי היה ה־MVP?</h3><p>בחירה אחת למשחק. אי אפשר לבחור את עצמך.</p></div></div><div className="mvp-grid">{players.map(p=><button type="button" key={p.user_id} className={mvp===p.user_id?'active':''} onClick={()=>setMvp(p.user_id)}><Crown size={17}/>{fullName(p.profiles)}</button>)}</div></div>
 <div className="rating-submit-bar"><div><strong>{completed===players.length?'סיימת לדרג את כולם':`נשארו ${players.length-completed} שחקנים`}</strong><p>אפשר לשמור גם דירוג חלקי ולהמשיך אחר כך.</p></div><Button onClick={()=>submit.mutate()} disabled={submit.isPending||completed===0}>{submit.isPending?'שומר...':'שמירת דירוגים'}</Button></div></>}</Card>:<Card className="empty-state"><Star size={34}/><h2>אין כרגע משחק פתוח לדירוג</h2><p>לאחר המשחק המנהל יפתח דירוג, והוא יופיע כאן אוטומטית.</p></Card>}
 <div><h2 className="mb-3 text-xl font-black">טבלת הקבוצה</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{board.map((p,i)=><Card key={p.id} className="flex items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#172b45] font-black">{i===0?<Trophy size={20}/>:i===1?<Medal size={20}/>:i+1}</div><div className="min-w-0 flex-1"><h2 className="truncate font-black">{`${p.first_name||''} ${p.last_name||''}`.trim()||'שחקן'}</h2><div className="mt-1 flex gap-3 text-xs text-[#94a3b8]"><span className="flex gap-1"><Star size={13}/>{p.avg_rating.toFixed(1)}</span><span>{p.rating_count} דירוגים</span><span>{p.mvp_count} MVP</span></div></div><Badge>#{i+1}</Badge></Card>)}</div></div></div>
}
