import {Activity,BarChart3,CalendarDays,Database,History,Home,Layers3,LogOut,Plus,Settings,Shield,UsersRound,UserRound,Zap} from 'lucide-react';
import {NavLink,Outlet,useNavigate} from 'react-router-dom';
import {cn} from '../lib/utils';
import {useGroup,canManage,isSystemAdmin} from '../hooks/useGroup';
import {useAuth} from '../contexts/AuthContext';
import AppInstallBanner from './AppInstallBanner';
import NotificationCenter from './NotificationCenter';
const base=[['/','בית',Home],['/groups','קבוצות',Layers3],['/availability','סקר',CalendarDays],['/squad','קבוצה',UsersRound],['/stats','סטטיסטיקות',BarChart3],['/activity','פעילות',Activity],['/history','היסטוריה',History]] as const;
export default function Layout(){const {data:g,memberships,setActiveGroupId}=useGroup();const navigate=useNavigate();const {profile,signOut}=useAuth();let links:any[]=[...base];if(canManage(g))links.push(['/admin','ניהול קבוצה',Shield],['/group-settings','הגדרות קבוצה',Settings]);if(isSystemAdmin(profile))links.push(['/system-admin','מערכת',Database]);const mobile=links.filter(([to])=>['/','/groups','/availability','/squad','/admin'].includes(to));return <div className="app-shell"><aside className="desktop-sidebar"><div className="brand-mark"><span>⚽</span><div><strong>TEAMUP</strong><small>Multi‑Club Platform</small></div></div><nav>{links.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' } className={({isActive})=>cn('side-link',isActive&&'active')}><Icon size={20}/><span>{label}</span></NavLink>)}</nav><div className="sidebar-profile"><NavLink to="/profile"><UserRound size={20}/><span>{profile?.first_name||'פרופיל'}</span></NavLink><button onClick={signOut} title="יציאה מהחשבון"><LogOut size={19}/></button></div></aside><div className="content-shell"><header className="desktop-topbar"><div><p>TEAMUP CLUB</p><div className="topbar-group-row"><span className="group-color-dot" style={{background:g?.group.theme_color||'#2563eb'}}/><h2>{g?.group.name||'הקבוצה שלי'}</h2>{memberships.length>1&&<select value={g?.group.id||''} onChange={e=>setActiveGroupId(e.target.value)}>{memberships.map(x=><option key={x.group.id} value={x.group.id}>{x.group.name}</option>)}</select>}</div></div><div className="topbar-actions"><NotificationCenter/><NavLink to="/profile" className="profile-chip"><UserRound size={19}/>{profile?.first_name||'פרופיל'}</NavLink></div></header><AppInstallBanner/><main className="page-wrap"><Outlet/></main>{canManage(g)&&<div className="quick-fab"><button title="פעולות מהירות" onClick={()=>navigate('/admin')}><Zap size={20}/><span>פעולות מהירות</span><Plus size={17}/></button></div>}</div><nav className="mobile-nav safe-bottom">{mobile.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/' } className={({isActive})=>cn('mobile-link',isActive&&'active')}><Icon size={20}/><span>{label}</span></NavLink>)}<NotificationCenter/></nav></div>}
