import {useEffect,useState} from 'react';
import {Bell,CheckCheck,ChevronLeft} from 'lucide-react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {useNavigate} from 'react-router-dom';
import {supabase} from '../lib/supabase';import {useAuth} from '../contexts/AuthContext';import {useRealtimeInvalidation} from '../hooks/useRealtime';
export default function NotificationCenter(){const {user}=useAuth();const [open,setOpen]=useState(false);const qc=useQueryClient();const navigate=useNavigate();const {data=[]}=useQuery({queryKey:['notifications',user?.id],enabled:!!user,queryFn:async()=>{const {data,error}=await supabase.from('notifications').select('*').eq('user_id',user!.id).order('created_at',{ascending:false}).limit(30);if(error)throw error;return data||[]}});useRealtimeInvalidation(`notifications-${user?.id}`,['notifications'],[['notifications',user?.id]],!!user);const unread=data.filter((x:any)=>!x.is_read).length;
 useEffect(()=>{if(!user)return;const c=supabase.channel(`device-notifications-${user.id}-${crypto.randomUUID()}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${user.id}`},async(payload:any)=>{if(Notification.permission==='granted'){const reg=await navigator.serviceWorker?.getRegistration();reg?.showNotification(payload.new.title||'TEAMUP',{body:payload.new.message||'',icon:'/icon-192.png',badge:'/icon-192.png',tag:payload.new.id,data:{entity_type:payload.new.entity_type,entity_id:payload.new.entity_id}})}}).subscribe();return()=>{void supabase.removeChannel(c)}},[user]);
 const markAll=async()=>{await supabase.from('notifications').update({is_read:true}).eq('user_id',user!.id).eq('is_read',false);qc.invalidateQueries({queryKey:['notifications',user?.id]})};
 const target=(n:any)=>n.entity_type==='match'&&n.entity_id?`/matches/${n.entity_id}`:n.entity_type==='poll'?`/availability${n.entity_id?`?poll=${n.entity_id}`:''}`:n.entity_type==='rating'?'/ratings':'/';
 const openNotification=async(n:any)=>{if(!n.is_read){await supabase.from('notifications').update({is_read:true}).eq('id',n.id).eq('user_id',user!.id);qc.setQueryData(['notifications',user?.id],(old:any[]|undefined)=>(old||[]).map(x=>x.id===n.id?{...x,is_read:true}:x))}setOpen(false);navigate(target(n))};
 return <div className="notification-center"><button className="icon-button" title="התראות" onClick={()=>setOpen(!open)}><Bell size={20}/>{unread>0&&<b>{unread}</b>}</button>{open&&<div className="notification-popover"><div className="notification-head"><div><strong>התראות</strong>{unread>0&&<small>{unread} לא נקראו</small>}</div><button title="סימון הכול כנקרא" onClick={markAll}><CheckCheck size={18}/></button></div>{data.length?data.map((n:any)=><button type="button" onClick={()=>openNotification(n)} key={n.id} className={`notification-item notification-link ${n.is_read?'':'unread'}`}><div><strong>{n.title}</strong><p>{n.message}</p><time>{new Date(n.created_at).toLocaleString('he-IL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></div><ChevronLeft size={18}/></button>):<p className="empty-note">אין התראות חדשות</p>}</div>}</div>}
