-- TEAMUP permissions and match workflow update
create or replace function public.has_group_permission(p_group uuid,p_permission text) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.group_members gm where gm.group_id=p_group and gm.user_id=(select auth.uid()) and gm.status='active' and (gm.role='admin' or gm.role='moderator' or exists(select 1 from public.member_permissions mp where mp.group_member_id=gm.id and mp.permission_key=p_permission)));
$$;
create or replace function public.is_group_admin(p_group uuid) returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.group_members where group_id=p_group and user_id=(select auth.uid()) and status='active' and role='admin');
$$;
drop policy if exists "matches admin insert" on public.matches;
drop policy if exists "matches admin update" on public.matches;
create policy "matches permitted insert" on public.matches for insert to authenticated with check(public.has_group_permission(group_id,'create_match') and created_by=(select auth.uid()));
create policy "matches permitted update" on public.matches for update to authenticated using(public.has_group_permission(group_id,'edit_match') or public.has_group_permission(group_id,'close_registration') or public.has_group_permission(group_id,'open_ratings'));
create or replace function public.delete_match(p_match_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare g uuid; begin select group_id into g from public.matches where id=p_match_id;if not public.is_group_admin(g) then raise exception 'רק מנהל ראשי יכול למחוק משחק';end if;delete from public.matches where id=p_match_id;end $$;
grant execute on function public.delete_match(uuid) to authenticated;
create or replace function public.set_match_registration(p_match_id uuid,p_open boolean) returns void language plpgsql security definer set search_path=public as $$ declare g uuid; begin select group_id into g from public.matches where id=p_match_id;if not public.has_group_permission(g,'close_registration') then raise exception 'אין הרשאה';end if;update public.matches set status=case when p_open then 'registration_open'::public.match_status else 'registration_closed'::public.match_status end where id=p_match_id;end $$;
grant execute on function public.set_match_registration(uuid,boolean) to authenticated;
create or replace function public.open_match_ratings(p_match_id uuid) returns void language plpgsql security definer set search_path=public as $$ declare m public.matches; begin select * into m from public.matches where id=p_match_id;if not public.has_group_permission(m.group_id,'open_ratings') then raise exception 'אין הרשאה';end if;if m.status not in ('registration_closed','teams_published','completed') then raise exception 'יש לסגור הרשמה וליצור קבוצות לפני פתיחת דירוג';end if;update public.matches set ratings_open=true,status='completed' where id=p_match_id;end $$;
grant execute on function public.open_match_ratings(uuid) to authenticated;
create or replace function public.generate_balanced_teams(p_match_id uuid) returns void language plpgsql security definer set search_path=public as $$
declare v_match public.matches;v_version int;v_team_ids uuid[];rec record;i int:=0;idx int;v_count int;
begin select * into v_match from public.matches where id=p_match_id;if not found or not public.has_group_permission(v_match.group_id,'generate_teams') then raise exception 'אין הרשאה';end if;if v_match.status<>'registration_closed' then raise exception 'אפשר לערבב קבוצות רק אחרי סגירת ההרשמה';end if;select count(*) into v_count from public.match_registrations where match_id=p_match_id and registration_status='confirmed';if v_count<2 then raise exception 'אין מספיק שחקנים';end if;select coalesce(max(generation_version),0)+1 into v_version from public.teams where match_id=p_match_id;v_team_ids:=array[]::uuid[];for idx in 1..v_match.team_count loop insert into public.teams(match_id,name,team_number,generation_version) values(p_match_id,'קבוצה '||idx,idx,v_version) returning id into rec;v_team_ids:=array_append(v_team_ids,rec.id);end loop;for rec in select mr.user_id,p.base_rating,p.preferred_position from public.match_registrations mr join public.profiles p on p.id=mr.user_id where mr.match_id=p_match_id and mr.registration_status='confirmed' order by (p.preferred_position='goalkeeper') desc,p.base_rating desc,random() loop idx:=(i % v_match.team_count)+1;insert into public.team_players(team_id,user_id,assigned_position,is_goalkeeper) values(v_team_ids[idx],rec.user_id,rec.preferred_position,rec.preferred_position='goalkeeper');i:=i+1;end loop;update public.matches set status='teams_published' where id=p_match_id;update public.teams set is_published=true where match_id=p_match_id and generation_version=v_version;end $$;
